# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Henrique Almeida"
weight = 1

[pt-br]
languageName = "Portugues - Brazil"
languagedirection = "ltr"
title = "Henrique Almeida"
weight = 1
